config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#index'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include RecordCache

  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include RecordCache
  include ArticleSearchable

  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
end

app/models/concerns/article_searchable.rb
module ArticleSearchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    index_name "articles_#{Rails.env}"

    settings analysis: analyzer_settings do
      mapping do
        indexes :id,          type: 'integer'
        indexes :user_id,     type: 'integer'
        indexes :title,       type: 'text', analyzer: 'custom_kuromoji'
        indexes :description, type: 'text', analyzer: 'custom_kuromoji'
      end
    end

    after_commit on: [:create] do
      __elasticsearch__.index_document
    end

    after_commit on: [:update] do
      __elasticsearch__.update_document
    end

    after_commit on: [:destroy] do
      __elasticsearch__.delete_document
    end

    def self.search(columns:, keywords:)
      __elasticsearch__.search(
        query: {
          multi_match: {
            query: keywords,
            fields: columns,
            type: 'cross_fields'
          }
        }
      ).records
    end
  end

  class_methods do
    def create_index!
      client = __elasticsearch__.client

      begin
        client.indices.delete index: index_name
      rescue StandardError
        nil
      end

      client.indices.create(
        index: index_name,
        body: {
          settings: settings.to_hash,
          mappings: mappings.to_hash
        }
      )
    end

    def analyzer_settings
      {
        analyzer: {
          custom_kuromoji: {
            type: 'custom',
            char_filter: [],
            tokenizer: 'kuromoji_tokenizer',
            filter: [
              'kuromoji_baseform',
              'kuromoji_part_of_speech',
              'cjk_width',
              'kuromoji_stemmer',
              'lowercase',
              'synonym'
            ]
          }
        },
        filter: {
          synonym: {
            type: 'synonym',
            synonyms: [
              '旅館,お宿,旅亭 => ホテル'
            ]
          }
        }
      }
    end
  end
end

app/models/concerns/record_cache.rb
module RecordCache
  extend ActiveSupport::Concern

  module ClassMethods
    def find(id)
      record = read_cache(id)

      return record if record

      record = super(id)

      write_cache(record)

      record
    end

    def cache_key(record_id)
      "#{to_s.downcase.pluralize}/#{record_id}"
    end

    def read_cache(record_id)
      serialized_record = Rails.cache.read(cache_key(record_id))

      return unless serialized_record

      Article.allocate.init_with(serialized_record)
    end

    def write_cache(record)
      serialized_record = {}
      record.encode_with(serialized_record)
      Rails.cache.write(cache_key(record.id), serialized_record)
    end

    def delete_cache(record)
      Rails.cache.delete(cache_key(record.id))
    end
  end

  def update(params)
    result = super(params)

    self.class.write_cache(self)

    result
  end

  def destroy
    result = super

    self.class.delete_cache(self)

    result
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def has?(model)
    id == model.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from Exception, with: :render_500 if Rails.env.production?

  rescue_from ActiveRecord::RecordNotFound, with: :render_404 if Rails.env.production?

  private

  def render_404(_error)
    render file: 'public/404.html', status: 404, layout: false
  end

  def render_500(_error)
    render file: 'public/500.html', status: 500, layout: false
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:q]
      @articles = Article.search(columns: [:title, :description], keywords: params[:q])
      return
    end

    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

    @article
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])

    fail ActiveRecord::RecordNotFound unless current_user.has?(@article)

    @article
  end

  def update
    @article = Article.find(params[:id])

    fail ActiveRecord::RecordNotFound unless current_user.has?(@article)

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])

    fail ActiveRecord::RecordNotFound unless current_user.has?(@article)

    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def login
    @user = User.find_by(name: params[:user_name])

    if @user.nil? || !@user.authenticate(params[:password])
      flash[:error] = 'Failed login'
      redirect_to root_path
      return
    end

    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :poster %><br>
    <%= form.select :user_name, @users.map{ |u| u.name } %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= form_with url: articles_path, method: :get, local: true do |form| %>
  <p>
    <%= form.label :keyword %><br>
    <%= form.text_field :q %>
  </p>

  <p>
    <%= form.submit "search" %>
  </p>
<% end %>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td>
        <%= link_to 'Destroy', article_path(article),
          method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Poster:</strong>
  <%= @article.user.name %>
</p>

<%= link_to 'Back', articles_path %>

app/views/home/home.html.erb
<h1>Home</h1>

<% if flash[:error] %>
  <div id="error_explanation">
    <%= flash[:error] %>
  </div>
<% end %>

<%= form_tag '/login' do %>
  <p>
    <%= label_tag :user_name %><br>
    <%= text_field_tag :user_name %>
  </p>

  <p>
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </p>

  <p>
    <%= submit_tag 'Login' %>
  </p>
<% end %>


<%= link_to 'New Account', new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to('Log out', destroy_user_session_path, method: :delete) %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New Account</h1>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>

    <p>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>